{% set name = "oast" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oast-{{ version }}.tar.gz
  sha256: 5797512920cfa2ab4a4fb325c570bd8d1bfad98fb99e2c8b75dd1c24e54cd7f6

build:
  entry_points:
    - analyze = oast.analyze:main
    - transform-image = oast.transform_image:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - joblib
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - spectral

test:
  imports:
    - oast
  commands:
    - pip check
    - analyze --help
    - transform-image --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jag426/oast
  summary: our awesome spectral toolbox
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jag426
